version: '3'
services:
  app:
    container_name: quantox-app
    build:
      dockerfile: ./dockerfile/Dockerfile
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '80:80'
    volumes:
      - '../:/var/www/html'
    networks:
      - task
    depends_on:
      - mysql

  mysql:
    container_name: quantox-mysql
    image: 'mysql/mysql-server:8.0'
    ports:
      - '3306:3306'
    command: ["--default-authentication-plugin=mysql_native_password"]
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'mysql-volume:/var/lib/mysql'
    networks:
      - task
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s

networks:
  task:
    driver: bridge

volumes:
  mysql-volume:
    driver: local
